[package]
name = "l3_5"
version = "0.1.0"
authors = ["Petru <smart__petea@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses="5.101.0"
